imports:
    - { resource: parameters.yml }
services:
    centrifugo.client:
        class: Kismia\CentrifugoBundle\Client\CentrifugoClient
        arguments: ["%centrifugo.apiendpoint%", "%centrifugo.secret%", "%centrifugo.transport%"]